### ISSUE TITLE
Vim 7.4 Function name must start with a capital

### ISSUE THREAD

**Issue by DelvarWorld** [thinca/vim-textobj-function-javascript#2]
On opening any file, a warning:

    Vim(function):E128: Function name must start with a capital or "s:": g:textobj_function_javascript_select(object_type)

And that's just the clean version. A second time it spit out a bunch more:

    E128: Function name must start with a capital or "s:": g:textobj_function_javascript_select(object_type)
    line   12:
    E133: :return not inside a function
    line  156:
    E700: Unknown function: g:textobj_function_javascript_select       

not sure if it's because it's invalidly declared?

**Comment by thinca** [comment]
Use latest version.
