### ISSUE TITLE
Regression since merging fat-arrow PR

### ISSUE THREAD

**Issue by edi9999** [thinca/vim-textobj-function-javascript#5]
With the following function : 

```
function foo(options) {
	return () => 1;
}
```

where the cursor is on the f of the `function` keyword, if I do : `daf` to `delete` `a` `function`, instead of deleting the full function, it stops at the end of the fat arrow function.

Eg I get : 

```
;
}
```

but the expected result is just empty.

**Comment by yasen-atanasov** [comment]
Thanks for finding this. PR: #6

**Comment by edi9999** [comment]
I confirm that it works. Thanks !
